# Generated by Django 2.0.4 on 2018-05-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50, verbose_name='Login')),
                ('Senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('DtExpiracao', models.DateField(max_length=10, verbose_name='DtExpiracao')),
                ('RA', models.CharField(max_length=7, verbose_name='RA')),
                ('Foto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('decricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('conteudo', models.CharField(max_length=255, verbose_name='Conteudo')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('extras', models.CharField(max_length=255, verbose_name='Extras')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Rotulo', models.CharField(max_length=255, verbose_name='Rotulo')),
                ('Status', models.CharField(max_length=255, verbose_name='Status')),
                ('DtInicioRespostas', models.DateField(max_length=10, verbose_name='DtInicioRespostas')),
                ('DtFimRespostas', models.DateField(max_length=10, verbose_name='DtFimRespostas')),
                ('IdAtividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50, verbose_name='Login')),
                ('Senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('DtExpiracao', models.DateField(max_length=10, verbose_name='DataExpiracao')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('Data', models.DateField(verbose_name='Data')),
                ('Status', models.CharField(max_length=255, verbose_name='Status')),
                ('PlanoDeEnsino', models.CharField(max_length=255, verbose_name='PlanoDeEnsino')),
                ('CargaHoraria', models.SmallIntegerField(verbose_name='Carga Horaria')),
                ('Competencias', models.CharField(max_length=255, verbose_name='Competencias')),
                ('Habilidades', models.CharField(max_length=255, verbose_name='Habilidades')),
                ('Ementa', models.CharField(max_length=255, verbose_name='Ementa')),
                ('ConteudoProgramatico', models.CharField(max_length=255, verbose_name='ConteudoProgramatico')),
                ('BibliografiaBasica', models.CharField(max_length=255, verbose_name='BibliografiaBasica')),
                ('BibliografiaComplementar', models.CharField(max_length=255, verbose_name='BibliografiaComplementar')),
                ('PercentualPratico', models.SmallIntegerField(verbose_name='PercentualPratico')),
                ('PercentualTeorico', models.SmallIntegerField(verbose_name='PercentualTeorico')),
                ('IdCoordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DtInicioMatricula', models.DateField(null=True, verbose_name='Data Inicio Matricula')),
                ('DtFimMatricula', models.DateField(null=True, verbose_name='Data Fim Matricula')),
                ('Ano', models.SmallIntegerField(verbose_name='Ano')),
                ('Semestre', models.SmallIntegerField(verbose_name='Semestre')),
                ('Turma', models.CharField(max_length=255, verbose_name='Turma')),
                ('Metodologia', models.CharField(max_length=255, null=True, verbose_name='Metodologia')),
                ('Recursos', models.CharField(max_length=255, null=True, verbose_name='Recursos')),
                ('CriterioAvaliacao', models.CharField(max_length=255, null=True, verbose_name='Criterio de Avaliacao')),
                ('PlanoDeAulas', models.CharField(max_length=255, null=True, verbose_name='Plano De Aulas')),
                ('IdCoordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coordenador')),
                ('IdCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('IdDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('Resposta', models.CharField(max_length=50, verbose_name='Resposta')),
                ('DtEntrega', models.DateField(max_length=10, verbose_name='Data Entrega')),
                ('Status', models.CharField(max_length=50, verbose_name='Status')),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('DtAvaliacao', models.DateField(max_length=10, verbose_name='DtAvaliacao')),
                ('Obs', models.CharField(max_length=50, verbose_name='Obs')),
                ('IdAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('IdAtividadeVinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AtividadeVinculada')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('referencia', models.CharField(max_length=255, verbose_name='Referencia')),
                ('conteudo', models.CharField(max_length=255, verbose_name='Conteudo')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('dtEnvio', models.DateTimeField(max_length=10, verbose_name='Data Envio')),
                ('dtResposta', models.DateField(max_length=10, verbose_name='Data Resposta')),
                ('resposta', models.CharField(max_length=255, verbose_name='Resposta')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50, verbose_name='Login')),
                ('Senha', models.CharField(max_length=50, verbose_name='Sena')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Email', models.CharField(max_length=100, verbose_name='Emil')),
                ('Celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('DtExpiracao', models.DateField(max_length=10, verbose_name='DtExpiracao')),
                ('Apelido', models.CharField(max_length=25, verbose_name='Apelido')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DtSolicitacao', models.DateField(verbose_name='DtSolicitacao')),
                ('Status', models.CharField(max_length=255, verbose_name='Status')),
                ('IdAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('IdCoordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coordenador')),
                ('IdDisciplinaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='IdProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='IdProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='IdDisciplinaOfertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='IdProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
    ]
